### ISSUE TITLE
Abandoned package

### ISSUE THREAD

**Issue by romather** [Intervention/imagecache#110]
![image](https://user-images.githubusercontent.com/47756883/78705092-53610d00-78e3-11ea-9c1b-47058462c4f1.png)
Package are abandoned !!!!

**Comment by olivervogel** [comment]
Will look into this.

**Comment by matthijs-neijenhuijs** [comment]
Can you fix it?

**Comment by hakimihamdan88** [comment]
any updates? @olivervogel

**Comment by vanushwashere** [comment]
any updates @olivervogel ?

**Comment by olivervogel** [comment]
SuperClosure is now replace with opis/closure. Use intervention/imagecache:dev-master for now. I will create a new release after some tests, soon.

**Comment by olivervogel** [comment]
[2.5.0](https://github.com/Intervention/imagecache/releases/tag/2.5.0) is available.
