### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by aavinseth** [Intervention/imagecache#117]
intervention/imagecache 2.4.2 does't allowed to upgrade laravel 7.x from laravel 8.x

**Comment by mahboobsabiry** [comment]
Same problem here, Anyone help please?

**Comment by xseguib** [comment]
https://github.com/Intervention/imagecache/pull/116 is waiting to be merged, 
Also there's a workaround meanwhile it's accepted, https://github.com/Intervention/imagecache/pull/116#issuecomment-688830052

**Comment by olivervogel** [comment]
Laravel 8 is now supported. Use `intervention/imagecache:dev-master` for now. I will create a new release after some tests, soon.

**Comment by olivervogel** [comment]
[2.5.0](https://github.com/Intervention/imagecache/releases/tag/2.5.0) is available.
