### ISSUE TITLE
URL manipulated images not updating when original file changes

### ISSUE THREAD

**Issue by enzomglb** [Intervention/imagecache#25]
Hello, it seems that URL manipulated images don't get updated when we make changes to the original file. Eg:

I call **imagecache/135x135/images/test.jpg** and I get a nice 135x135 thumbnail from my custom template.

But if I modify the original image...
`Image::make('images/test.jpg')->greyscale()->save();`

... and the hit again **imagecache/135x135/images/test.jpg** I'm going to get the exact same thumbnail as the beginning since it's going to load the cached version of the thumbnail, ignoring the changes on the original image.

Maybe it shouldn't load the cached version when its modification time is older than the original's file one.

Thanks for your time and effort with this package!

**Comment by guilhermeaiolfi** [comment]
The old cached image file will live forever in the filesystem? It seems that way. Shouldn't it remove the old ones when the new is generated?
