### ISSUE TITLE
Composer Update error using Laravel 5

### ISSUE THREAD

**Issue by alexleonard** [Intervention/imagecache#33]
Hey there,

I was able to install intervention/image 2.0.17 but trying to install intervention/imagecache 2.0.6 gives the following error:

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for intervention/imagecache 2.0.6 -> satisfiable by intervention/imagecache[2.0.6].
        - Conclusion: remove jeremeamia/SuperClosure 2.0.0
        - laravel/framework 5.0.x-dev requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0].
        - laravel/framework 5.0.x-dev requires jeremeamia/superclosure ~2.0 -> satisfiable by jeremeamia/SuperClosure[2.0.0].
        - Conclusion: don't install jeremeamia/SuperClosure 2.0.0
        - Installation request for laravel/framework 5.0.*@dev -> satisfiable by laravel/framework[5.0.x-dev].

Is there any current workaround or best to wait until L5 is fully released?

**Comment by olivervogel** [comment]
Just updated. `intervention/image` and `intervention/imagecache`. Should work now.

**Comment by alexleonard** [comment]
Thanks so much @olivervogel :)

Just tested it and composer updated with no issue :) Thanks for the speedy action :+1:
