### ISSUE TITLE
Laravel Cache Store

### ISSUE THREAD

**Issue by thangngoc89** [Intervention/imagecache#35]
Is there anyway I can choose Laravel Cache Store for imagecache? Because I'm using Redis as default cache store and it's a big resources wasting if use Redis as Image Cache.

**Comment by olivervogel** [comment]
Yes there is a way, but not out of the box. I would create a custom Illuminate Cache instance inserting it into a manually created imagecache. With Laravels IOC container this should be no problem.

**Comment by thangngoc89** [comment]
Thank you for your point out. I'll give it a try

**Comment by thangngoc89** [comment]
@olivervogel  After a while, I think create a new class and overide imagecache method is the simplest way to achive this function.
