### ISSUE TITLE
Recursive search in given paths

### ISSUE THREAD

**Issue by thorem** [Intervention/imagecache#36]
Is it possible to do recursive searches on the given storage paths?

**Comment by olivervogel** [comment]
You can add subdirectories to the path, but child directories will not be searched out of the box.

**Comment by wesleydb** [comment]
Can you add recursive searches? My product photos is stored under each product id, like /products/1/one.jpg, /products/1/two.jpg,  /products/1000/image.jpg etc.

**Comment by Luddinus** [comment]
@wesleydb Did you find a solution?

**Comment by vadimsg** [comment]
@olivervogel what's the point of this package if it can't cache images from big dynamic folder structures? It's a normal practice to store files under name/category or id folder names.
Could you add wildcards or a config variable for recursive search at least?
