### ISSUE TITLE
Laravel 5 Filesystem/Cloud Storage

### ISSUE THREAD

**Issue by benswinburne** [Intervention/imagecache#37]
Do you have any plans to enable the use of other storage engines for the cache, perhaps utilising L5's new storage abstraction?

It'd be useful to be able to host cached images in S3 etc. At the moment, my load balanced application caches the image on each node which is obviously not ideal.

**Comment by olivervogel** [comment]
As far as I know Laravel's Cache has just `filesystem` as a driver. The whole Filesystem / Cloud Storage thing is a complete different story.

**Comment by benswinburne** [comment]
Are there any plans to implement anything like this? It'd be nice to be able to serve cached images straight from say S3

**Comment by olivervogel** [comment]
I'm currently more focused on the image manipulation side. Maybe you can give [Glide](http://glide.thephpleague.com/) a try, it uses Intervention Image and Flysystem for storage, so S3 should be possible.

**Comment by canfiax** [comment]
+1 This is a heavy requirement for our setup as we do not host storage/media on our production server.

**Comment by olivervogel** [comment]
Should be implemented by Illuminate/Cache.
