### ISSUE TITLE
vendor:publish not showing any configs

### ISSUE THREAD

**Issue by Failcookie** [Intervention/imagecache#39]
I am upgrading my system with a fresh start in Laravel 5. Imagecache for L4 came with a config file, so I am assuming L5 version has one as well. When I do a "php artisan vendor:publish" I am receiving a "Noting to publish" error. Am I missing something in the setup?

**Comment by olivervogel** [comment]
You added the Service Provider?

**Comment by Failcookie** [comment]
Yes, both
`'Intervention\Image\ImageServiceProvider',` and `'Image'     => 'Intervention\Image\Facades\Image',`

**Comment by Failcookie** [comment]
I just realized that the `intervention/image` package did not move over the config vendor files either. Is there an additional Laravel step that I may have missed?

**Comment by olivervogel** [comment]
Make sure you're on version >=2.1.

**Comment by Failcookie** [comment]
`"intervention/image": "~2.1",
"intervention/imagecache": "~2.1"` are my listings. Sorry if I am being too vague :\

**Comment by olivervogel** [comment]
Sorry, I'm currently out of ideas. Publishing the config file works for me and apparently also for other users.

**Comment by Failcookie** [comment]
Alright. I will start a fresh L5 and see if I can find what happened. Thank you!
