### ISSUE TITLE
Laravel 5 Route bug

### ISSUE THREAD

**Issue by PhilMarc** [Intervention/imagecache#42]
When trying to use the artisan command `php artisan route:cache`, I get this error:

![](http://i.imgur.com/1cMDyHI.png)

The ImageCache route from the config/imagecache.php also throws an error when I run the artisan command `php artisan config:cache` and then try to access a page of my app:

![](http://i.imgur.com/QZcjSQc.png)

Here is the line 268:

![](http://i.imgur.com/Rf7EwlS.png)

The content of the array isn't cached properly. (Otherwise, my imagecache installation works fine when I don't use the cached config file).

Last but not least, and I'm not sure it's related or not, everytime I access a cached image, I get the `Undefined index: _sf2_meta`:

![](http://i.imgur.com/Q3nJ4d3.png)

Here is the compiled.php on line 10981:

![](http://i.imgur.com/M6BlqEN.png)

It seems to be a recurring problem on laravel 5 due to the fact that you can't change session drivers, but I have no clue how to fix this.

**Comment by tylercubell** [comment]
I'm also having this problem. Apparently closures cannot be cached using `config:cache` or `route:cache` in Laravel 5. 

The temporary solution is to edit the config file in `/vendor/intervention/imagecacge/src/config/config.php` and replace the closures with `false`.

```php
    'templates' => array(

        'small' => false,
        'medium' => false,
        'large' => false

    ),
```

**Comment by olivervogel** [comment]
Apparently route caching with Closures is and will be [not supported](https://github.com/laravel/framework/issues/7319) by Laravel.

**Comment by olivervogel** [comment]
Routing is [now](0794835d12636ae0f9bd9263cfe93f35fb842c24) handled by a Controller, so caching should be possible
