### ISSUE TITLE
Closures in imagecache config

### ISSUE THREAD

**Issue by rauanmaemirov** [Intervention/imagecache#45]
Closures in imagecache config breaks laravel 5's config cache (and it would break zf2's config cache, too).
I figured it's serialisation issue. Is it really necessary to setup resize logic in config file?

**Comment by olivervogel** [comment]
Templates in config are [now](7edc830d19733a40afae5641aabf0acf6be1961b) defined by classnames for image [filters](http://image.intervention.io/use/filters), so caching should be possible. `intervention/image` needs to be update to newest version too.
