### ISSUE TITLE
URL based image manipulation broken with IC 2.1.4

### ISSUE THREAD

**Issue by edubuc** [Intervention/imagecache#46]
Hi,

I updated (composer update) to intervention/image 2.1.4 then my url based image manipulation was broken, with message "unable to load Intervention/Image/ImageCacheRouteController"

After searching for file permission and so on, i give up and finally turn back to intervention image 2.1.3. Is anyone know what happened in intervention image 2.1.4 ?

**Comment by olivervogel** [comment]
Thanks for reporting. I just tagged a new `imagecache` version. So if you update both `intervention/image` and `intervention/imagecache` to the newest versions, everything should work fine.
