### ISSUE TITLE
download option within url manipulation

### ISSUE THREAD

**Issue by atmediauk** [Intervention/imagecache#54]
Hello,

Just wondering if its possible to download an image (based on the original) when using image cache and url manipulation.

For example it would be accessed just like **original** keyword only with the keyword **download** instead. Sort of like: http://random.app/media/cache/download/myimage.jpg

Not sure if its the right way but I tried creating a filter but keep getting errors.

The error 
```
ErrorException in ImageCache.php line 319:
Undefined property: Illuminate\Http\Response::$encoded
```

Part of the filter
```
    public function applyFilter(Image $image)
    {
        $response = Response::make($image->encode());
        $response->header('Content-Type', $image->mime);
        return $response;
    }
```

Thanks for your time

**Comment by olivervogel** [comment]
Just create a filter, which does nothing and create an `download` template.

```php
 public function applyFilter(\Intervention\Image\Image $image)
{
       return $image;
}
```

At the moment it is only possible to get the browser to display the image and not "download" it.

**Comment by atmediauk** [comment]
Thats @olivervogel Yeah thats what I had previously but was hoping to start an actual file download. I'll just trigger the save as with javascript for now I think. Thanks for your help.

**Comment by olivervogel** [comment]
I added a predefined `download` template in 7936b90e695daee1aafbd25221815352ef97bcbc. Please update to the latest version.

**Comment by atmediauk** [comment]
Yey, thank you!
