### ISSUE TITLE
How to use with Amazon AWS?

### ISSUE THREAD

**Issue by canfiax** [Intervention/imagecache#55]
Is there any way it can integrate it with Amazon AWS? Laravel 5 has some cool updates to the filesystem (https://laracasts.com/series/whats-new-in-laravel-5/episodes/6) which makes it redicuisly easy to use a cloud.

Really curios about this.

**Comment by olivervogel** [comment]
Imagecache uses the Cache component of Laravel, which is a complete different thing than the Filesystem.

**Comment by canfiax** [comment]
OK, so it will not be necessary to cache images in the sky? I am thinking of space.
