### ISSUE TITLE
Imagecache URL routing not working on live server

### ISSUE THREAD

**Issue by dexterb2992** [Intervention/imagecache#57]
This is my imagecache config.php 
![screenshot_2](https://cloud.githubusercontent.com/assets/4485993/10571112/52210b1a-766e-11e5-8538-de9f56089a18.png)

localhost routes: 

![local routes](https://cloud.githubusercontent.com/assets/4485993/10571137/8e440160-766e-11e5-96f4-6f114fbdf0b4.png)

live site routes:

![live server routes](https://cloud.githubusercontent.com/assets/4485993/10571142/950d28d2-766e-11e5-9036-41a3c085960c.png)

Note: GD library is installed on live site, and is supported.

On my localhost, the url routing works great, with no problem at all. However, when I try to run on live site, the url routing doesn't work at all. Why? can anyone tell me, what I am missing?

**Comment by abnersajr** [comment]
Try to change your custom templates for an folder insider your App.
Create `App\Filters`
then create your filters file only with chars, without numbers. 
` 'templates' => array(
        'small' => 'Intervention\Image\Templates\Small',
        'medium' => 'Intervention\Image\Templates\Medium',
        'large' => 'Intervention\Image\Templates\Large',
        'thumb' => 'App\Filters\Thumb',
        'slider' => 'App\Filters\Slider'
    ),`

Example of mine config.
```
And one of my filters:
<?php
namespace App\Filters;

use Intervention\Image\Image;
use Intervention\Image\Filters\FilterInterface;

class Thumb implements FilterInterface
{
    public function applyFilter(Image $image)
    {
        return $image->fit(260, 160)->encode('jpg',68);
    }
}
```

My problem was the name of folder in config. I put App\filters
the name of my folder is App\Filters

Seems to be Case Sensitive, so be carefull
