### ISSUE TITLE
URL Manipulation - Cache does not change when original image changes

### ISSUE THREAD

**Issue by maltalk** [Intervention/imagecache#65]
Hi!

Using:
Apache/2.4.7 (Ubuntu)
PHP 5.5.9
Laravel 5.2.41
intervention/image 2.3.7
intervention/imagecache 2.3.3
GD extension and filesystem cache.

When the original files changes, keeps serving the old one.
As seen in #25 , that is supposed to work but no idea why is not working now.

Thanks for your time and effort with this package, it's awesome!

**Comment by sandervanhooft** [comment]
Please read #25 again, it concludes that it is NOT supported and it is normal behaviour.
