### ISSUE TITLE
Error when using intervention object

### ISSUE THREAD

**Issue by skechele** [Intervention/imagecache#72]
Hi,

if try to make a new Intervention Object from a existing one, inside the cache, it fails on my Linux System (not on windows though)
![intevention](https://cloud.githubusercontent.com/assets/2145466/20573867/2fb525fe-b1b2-11e6-9a7c-241dabde5af5.PNG)

This would be how it is called:
```
Intervention::cache(function($image) use($width) {
            $image = $image->make($this->interventionObject);
            $image->resize($width, null, function ($constraint) {
                $constraint->aspectRatio();
            });
        }, 1440, true);
```

Is it a bug or is my Linux System somehow messed up?

**Comment by TomFyuri** [comment]
Have you found out why this happens? Current workaround:
1) Open ImageCache.php.
2) Find line "if ($this->isFile($data)) {".
3) Insert before that line, this one "if (strlen($data)<4096)".

**Comment by skechele** [comment]
I think it's just a "bug" in the is_file-Function. Didnt really know what to do, so I just forked it and applied a fix.
You can find my fix for it here: https://github.com/skechele/imagecache/commit/9ff895686559c33e5b1f97348b9570ebfbf23e18

**Comment by olivervogel** [comment]
Included workaround of @skechele.

**Comment by skechele** [comment]
Sehr geehrte Damen und Herren,

ich bin bis voraussichtlich 21. Juli 2017 nicht im Büro.
Ich werde Ihre E-Mails ab dem 24. Juli 2017 beantworten.

In dringenden Fällen können Sie sich an meine Kollegen wenden:
Telefon: 0731 938060
E-Mail: info@deitron.de

Freundliche Grüße,
Stefan Kechele
